{% set name = "libgpiod" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://git.kernel.org/pub/scm/libs/{{ name }}/{{ name }}.git/snapshot/{{ name }}-{{ version }}.tar.gz
  sha256: 8d80ea022ae78122aa525308e7423b83064bff278fcd9cd045b94b4f81f8057d

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - autoconf
    - autoconf-archive
    - pkg-config
    - automake
    - libtool

outputs:
  - name: {{ name }}
    script: build_base.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - make
        - autoconf
        - autoconf-archive
        - pkg-config
        - automake
        - libtool
    test:
      commands:
        - test -f "${PREFIX}/lib/libgpiod.so"
        - test -f "${PREFIX}/lib/libgpiod.a"
        - test -f "${PREFIX}/lib/libgpiod.so.3"
        - test -f "${PREFIX}/lib/libgpiod.so.3.1.2"
        - test -f "${PREFIX}/include/gpiod.h"
        - test -f "${PREFIX}/lib/pkgconfig/libgpiod.pc"
    about:
      license: LGPL-2.1-or-later
      license_file:
        - LICENSES/LGPL-2.1-or-later.txt

  - name: gpiod-tools
    script: build_tools.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - make
        - autoconf
        - autoconf-archive
        - pkg-config
        - automake
        - libtool
      host:
        - {{ pin_subpackage('libgpiod', exact=True) }}
      run:
        - {{ pin_subpackage('libgpiod', exact=True) }}
    test:
      commands:
        - test -f "${PREFIX}/bin/gpiodetect"
        - test -f "${PREFIX}/bin/gpioget"
        - test -f "${PREFIX}/bin/gpioinfo"
        - test -f "${PREFIX}/bin/gpionotify"
        - test -f "${PREFIX}/bin/gpioset"
        - test -f "${PREFIX}/bin/gpiomon"
    about:
      license: GPL-2.0-or-later
      license_file:
        - LICENSES/GPL-2.0-or-later.txt

  - name: gpiod-python
    script: build_py.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - autoconf
        - swig
      host:
        - {{ pin_subpackage('libgpiod', exact=True) }}
        - wheel
        - setuptools
        - python >=3.9
        - pip
        - packaging
      run:
        - python >=3.9
        - {{ pin_subpackage('libgpiod', exact=True) }}
    test:
      imports:
        - gpiod
      commands:
        - pip check
      requires:
        - pip
    about:
      license: LGPL-2.1-or-later
      license_file:
        - LICENSES/LGPL-2.1-or-later.txt

about:
  home: https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/about
  summary: C library and tools for interacting with the linux GPIO character device (gpiod stands for GPIO device)
  license: LGPL-2.1-or-later AND GPL-2.0-or-later
  license_file:
    - LICENSES/LGPL-2.1-or-later.txt
    # used in gpio-tools
    - LICENSES/GPL-2.0-or-later.txt

extra:
  recipe-maintainers:
    - pavelzw
    - ytausch
    - freundTech
